{"failedCount":1,"prefixedPath":"src\/test\/java\/modules\/get\/modules-get.feature","packageQualifiedName":"src.test.java.modules.get.modules-get","loopIndex":-1,"relativePath":"src\/test\/java\/modules\/get\/modules-get.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":2299008700,"millis":2299.0087,"status":"passed"},"step":{"background":true,"line":4,"prefix":"*","index":0,"text":"call read(\"..\/..\/user\/token\/users-token-post.feature@token\")"},"callResults":[{"failedCount":0,"prefixedPath":"src\/test\/java\/modules\/get\/..\/..\/user\/token\/users-token-post.feature","packageQualifiedName":"src.test.java.modules.get.user.token.users-token-post","loopIndex":-1,"relativePath":"src\/test\/java\/modules\/get\/..\/..\/user\/token\/users-token-post.feature","scenarioResults":[{"sectionIndex":0,"stepResults":[{"result":{"nanos":2913600,"millis":2.9136,"status":"passed"},"step":{"line":6,"prefix":"Given","index":0,"text":"url \"https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\""}},{"result":{"nanos":42287800,"millis":42.2878,"status":"passed"},"step":{"line":7,"prefix":"And","index":1,"text":"request {\"user\": \"ruben1\", \"password\": \"ruben123\"}"}},{"result":{"nanos":1940897100,"millis":1940.8971,"status":"passed"},"step":{"line":8,"prefix":"When","index":2,"text":"method post"},"stepLog":"22:34:40.464 request:\n1 > POST https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/users\/token\/\n1 > Content-Type: application\/json; charset=UTF-8\n1 > Content-Length: 39\n1 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n1 > Connection: Keep-Alive\n1 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n1 > Accept-Encoding: gzip,deflate\n{\"user\":\"ruben1\",\"password\":\"ruben123\"}\n\n22:34:42.055 response time in milliseconds: 1589\n1 < 200\n1 < date: Tue, 05 Mar 2024 03:34:41 GMT\n1 < server: envoy\n1 < content-length: 166\n1 < content-type: application\/json\n1 < x-envoy-upstream-service-time: 732\n{\"access_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTcwOTY4Mi4zNTY2ODU0fQ.TsG-lycPqo7NbCfFQ7Tm_HIltb0Tu0Lyz9G76aWFRCQ\"}\n\n"},{"result":{"nanos":6015600,"millis":6.0156,"status":"passed"},"step":{"line":9,"prefix":"Then","index":3,"text":"status 200"}},{"result":{"nanos":36853800,"millis":36.8538,"status":"passed"},"step":{"line":10,"prefix":"*","index":4,"text":"def token = $.access_token"}}],"line":5,"description":"","durationMillis":2028.9679,"failed":false,"tags":["token"],"executorName":"main","name":"Post a token","startTime":1709609680068,"refId":"[1:5]","endTime":1709609682100,"exampleIndex":-1}],"callDepth":1,"name":"JWT Token Feature","description":"","resultDate":"2024-03-04 10:34:42 p.\u202Fm.","durationMillis":2028.9679,"passedCount":1}]},{"result":{"nanos":21915200,"millis":21.9152,"status":"passed"},"step":{"background":true,"line":5,"prefix":"*","index":1,"text":"header Authorization = \"Bearer \" + token"}},{"result":{"nanos":15782700,"millis":15.7827,"status":"passed"},"step":{"background":true,"line":6,"prefix":"*","index":2,"text":"print token"},"stepLog":"22:34:42.140 [print] eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTcwOTY4Mi4zNTY2ODU0fQ.TsG-lycPqo7NbCfFQ7Tm_HIltb0Tu0Lyz9G76aWFRCQ \n"},{"result":{"nanos":658500,"millis":0.6585,"status":"passed"},"step":{"line":11,"prefix":"Given","index":0,"text":"url 'https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/'"}},{"result":{"nanos":847827400,"millis":847.8274,"status":"passed"},"step":{"line":12,"prefix":"When","index":1,"text":"method get"},"stepLog":"22:34:42.142 request:\n2 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/\n2 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTcwOTY4Mi4zNTY2ODU0fQ.TsG-lycPqo7NbCfFQ7Tm_HIltb0Tu0Lyz9G76aWFRCQ\n2 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n2 > Connection: Keep-Alive\n2 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n2 > Accept-Encoding: gzip,deflate\n\n\n22:34:42.464 request:\n3 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/\n3 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTcwOTY4Mi4zNTY2ODU0fQ.TsG-lycPqo7NbCfFQ7Tm_HIltb0Tu0Lyz9G76aWFRCQ\n3 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n3 > Connection: Keep-Alive\n3 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n3 > Accept-Encoding: gzip,deflate\n\n\n22:34:42.627 request:\n4 > GET https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/\n4 > Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoicnViZW4xIiwiZXhwaXJlcyI6MTcwOTcwOTY4Mi4zNTY2ODU0fQ.TsG-lycPqo7NbCfFQ7Tm_HIltb0Tu0Lyz9G76aWFRCQ\n4 > Host: funcoeback-dev-ceqh.3.us-1.fl0.io\n4 > Connection: Keep-Alive\n4 > User-Agent: Apache-HttpClient\/4.5.13 (Java\/21.0.2)\n4 > Accept-Encoding: gzip,deflate\n\n\n22:34:42.977 response time in milliseconds: 350\n4 < 500\n4 < date: Tue, 05 Mar 2024 03:34:42 GMT\n4 < server: envoy\n4 < content-length: 2600\n4 < content-type: text\/plain; charset=utf-8\n4 < x-envoy-upstream-service-time: 244\nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\n\n"},{"result":{"nanos":148900,"errorMessage":"status code was: 500, expected: 200, response time in milliseconds: 350, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/modules\/get\/modules-get.feature:13","millis":0.1489,"status":"failed"},"step":{"line":13,"prefix":"Then","index":2,"text":"status 200"},"stepLog":"22:34:42.990 src\/test\/java\/modules\/get\/modules-get.feature:13\nThen status 200\nstatus code was: 500, expected: 200, response time in milliseconds: 350, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/modules\/get\/modules-get.feature:13\n"}],"line":10,"description":"","durationMillis":3185.3414,"failed":true,"error":"status code was: 500, expected: 200, response time in milliseconds: 350, url: https:\/\/funcoeback-dev-ceqh.3.us-1.fl0.io\/modules\/all\/, response: \nTraceback (most recent call last):\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/middleware\/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 762, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 782, in app\n    await route.handle(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 297, in handle\n    await self.app(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 77, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 64, in wrapped_app\n    raise exc\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/_exception_handler.py\", line 53, in wrapped_app\n    await app(scope, receive, sender)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/starlette\/routing.py\", line 72, in app\n    response = await func(request)\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 315, in app\n    content = await serialize_response(\n  File \"\/layers\/paketo-buildpacks_pip-install\/packages\/lib\/python3.10\/site-packages\/fastapi\/routing.py\", line 155, in serialize_response\n    raise ResponseValidationError(\nfastapi.exceptions.ResponseValidationError: 1 validation errors:\n  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None, 'url': 'https:\/\/errors.pydantic.dev\/2.5\/v\/model_attributes_type'}\n\n\nsrc\/test\/java\/modules\/get\/modules-get.feature:13","executorName":"main","name":"Get a modules","startTime":1709609679779,"refId":"[1:10]","endTime":1709609682990,"exampleIndex":-1}],"callDepth":0,"name":"Get modules on request","description":"","resultDate":"2024-03-04 10:34:42 p.\u202Fm.","durationMillis":3185.3414,"passedCount":0}